{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "echo-operator.fullname" . }}
  labels:
    {{- include "echo-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "echo-operator.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "echo-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
