{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "echo-operator.fullname" . }}
  labels:
    {{- include "echo-operator.labels" . | nindent 4 }}
  {{- with .Values.metrics.service.additionalLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.metrics.service.annotations }}
  annotations:
    {{ toYaml .Values.metrics.service.annotations | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - name: {{ .Values.metrics.service.portName }}
      port: {{ .Values.metrics.service.port }}
      targetPort: metrics
  selector:
    {{- include "echo-operator.selectorLabels" . | nindent 4 }}
{{- end }}
