apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: echoes.example.com
spec:
  group: example.com
  names:
    kind: Echo
    plural: echoes
    singular: echo
    shortNames:
      - echo
  scope: Namespaced
  versions:
    - name: v1
      subresources:
        status: {}
      additionalPrinterColumns:
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.replicas
          name: Replicas
          type: string
        - jsonPath: .status.readyReplicas
          name: Ready Replicas
          type: string
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - metadata
            - spec
          properties:
            apiVersion:
              description: |-
                APIVersion defines the versioned schema of this representation of an object.
                Servers should convert recognized schemas to the latest internal value, and
                may reject unrecognized values.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
              type: string
            kind:
              description: |-
                Kind is a string value representing the REST resource this object represents.
                Servers may infer this from the endpoint the client submits requests to.
                Cannot be updated.
                In CamelCase.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - replicas
              properties:
                replicas:
                  type: integer
                  format: int32
            status:
              type: object
              properties:
                availableReplicas:
                  type: integer
                  format: int32
                  description: The number of available replicas.
                observedGeneration:
                  type: integer
                  format: int64
                  description: The most recent generation observed by the controller.
                readyReplicas:
                  type: integer
                  format: int32
                  description: The number of replicas that are ready.
                replicas:
                  type: integer
                  format: int32
                  description: The number of desired replicas.
                updatedReplicas:
                  type: integer
                  format: int32
                  description: The number of replicas that have been updated to the latest revision.
