---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kaniop
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: kaniop
rules:
  - apiGroups: ["example.com"]
    resources: ["echoes"]
    verbs:
      - list
      - watch
      - patch
      - update
      - delete
      - create
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs:
      - patch
      - update
      - delete
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: default
  name: kaniop
subjects:
  - kind: ServiceAccount
    namespace: default
    name: kaniop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kaniop
