{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kaniop.serviceAccountName" . }}
  labels:
    {{- include "kaniop.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{ toYaml .Values.serviceAccount.annotations | indent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
