[package]
name = "kaniop"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "kaniop"
path = "src/main.rs"

[dependencies]
kaniop_operator = { path = "../../libs/operator", version = "0.0.0" }
tokio = { version = "1.40", features = ["macros", "rt-multi-thread"] }
kube = { version = "0.95", default-features = true, features = ["derive", "runtime"] }
k8s-openapi = { version = "0.23", default-features = false, features = ["v1_30"] }
futures = "0.3"
