[package]
name = "kaniop"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "kaniop"
path = "src/main.rs"

[dependencies]
kaniop_operator = { path = "../../libs/operator", version = "0.0.0" }
clap = { workspace = true, features = ["std", "derive", "cargo", "env"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
actix-web = "4.9.0"
futures = "0.3"
anyhow = "1.0"
