apiVersion: v2
name: kaniop
description: Kanidm Operator chart
type: application
version: 0.0.0
appVersion: 0.0.0
annotations:
  artifacthub.io/crds: |
    - kind: Echo
      version: v1
      name: echoes.example.com
      displayName: Echo
      description: |
        Example CRD
