name: Helm
on:
  push:
    branches: [master]
    tags:
      - v*
  pull_request:
    branches: [master]

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4.2.0
      - name: Lint Helm charts
        working-directory: ./charts
        run: make lint
      - name: Test Helm charts
        working-directory: ./charts
        run: make test
